// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ofhwpywyuwykvfxhwpoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9maHdweXd5dXd5a3ZmeGh3cG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY3NTg2ODgsImV4cCI6MjA4MjMzNDY4OH0.zteQmHxGUdS6dPt-8tNrke5YFSBJd2LrXjQX58UEKNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);